apiVersion: v2
name: testkube-api
description: A Helm chart for Testkube api
type: application
version: 2.1.65
appVersion: 2.1.65
dependencies:
  - name: global
    version: 0.1.2
    repository: "file://../global"
